
// List
export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';

// Single detail
export const FETCH_CLIENT_DETAIL_REQUEST = 'FETCH_CLIENT_DETAIL_REQUEST';
export const FETCH_CLIENT_DETAIL_SUCCESS = 'FETCH_CLIENT_DETAIL_SUCCESS';
export const FETCH_CLIENT_DETAIL_FAILURE = 'FETCH_CLIENT_DETAIL_FAILURE';